// <auto-generated />
using System;
using Kontaktlisteregisteret.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kontaktlisteregisteret.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811115831_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.Abonnementsliste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpprettetAv")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VirksomhetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VirksomhetId");

                    b.ToTable("Abonnementslister");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.Abonnent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbonnementslisteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kilde")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LagtTilAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AbonnementslisteId", "Epost")
                        .IsUnique();

                    b.ToTable("Abonnenter");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.Adresseliste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("EkskluderteJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LåstAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpprettetAv")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VirksomhetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VirksomhetId");

                    b.ToTable("Adresselister");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.AdresselisteAbonnementsliste", b =>
                {
                    b.Property<int>("AdresselisteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbonnementslisteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rekkefølge")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdresselisteId", "AbonnementslisteId");

                    b.HasIndex("AbonnementslisteId");

                    b.ToTable("AdresselisteAbonnementslister");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.AdresselisteMottaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdresselisteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoAdresse")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KildeAbonnementslisteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KildeMålgruppeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Visningsnavn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdresselisteId");

                    b.HasIndex("RecipientId");

                    b.ToTable("AdresselisteMottakere");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.AdresselisteMålgruppe", b =>
                {
                    b.Property<int>("AdresselisteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MålgruppeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rekkefølge")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdresselisteId", "MålgruppeId");

                    b.HasIndex("MålgruppeId");

                    b.ToTable("AdresselisteMålgrupper");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NaceCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgForm")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.TargetGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DynamicCriteriaJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VirksomhetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("VirksomhetId");

                    b.ToTable("TargetGroups");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.TargetGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoAdresse")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Visningsnavn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("TargetGroupId", "RecipientId");

                    b.ToTable("TargetGroupMembers");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.Virksomhet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OnboardetAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnboardetAv")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orgnr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Orgnr")
                        .IsUnique();

                    b.ToTable("Virksomheter");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.Abonnementsliste", b =>
                {
                    b.HasOne("Kontaktlisteregisteret.Web.Data.Virksomhet", "Virksomhet")
                        .WithMany()
                        .HasForeignKey("VirksomhetId");

                    b.Navigation("Virksomhet");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.Abonnent", b =>
                {
                    b.HasOne("Kontaktlisteregisteret.Web.Data.Abonnementsliste", "Abonnementsliste")
                        .WithMany("Abonnenter")
                        .HasForeignKey("AbonnementslisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abonnementsliste");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.Adresseliste", b =>
                {
                    b.HasOne("Kontaktlisteregisteret.Web.Data.Virksomhet", "Virksomhet")
                        .WithMany()
                        .HasForeignKey("VirksomhetId");

                    b.Navigation("Virksomhet");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.AdresselisteAbonnementsliste", b =>
                {
                    b.HasOne("Kontaktlisteregisteret.Web.Data.Abonnementsliste", "Abonnementsliste")
                        .WithMany()
                        .HasForeignKey("AbonnementslisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontaktlisteregisteret.Web.Data.Adresseliste", "Adresseliste")
                        .WithMany("Abonnementslister")
                        .HasForeignKey("AdresselisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abonnementsliste");

                    b.Navigation("Adresseliste");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.AdresselisteMottaker", b =>
                {
                    b.HasOne("Kontaktlisteregisteret.Web.Data.Adresseliste", "Adresseliste")
                        .WithMany("Mottakere")
                        .HasForeignKey("AdresselisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontaktlisteregisteret.Web.Data.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adresseliste");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.AdresselisteMålgruppe", b =>
                {
                    b.HasOne("Kontaktlisteregisteret.Web.Data.Adresseliste", "Adresseliste")
                        .WithMany("Målgrupper")
                        .HasForeignKey("AdresselisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontaktlisteregisteret.Web.Data.TargetGroup", "Målgruppe")
                        .WithMany()
                        .HasForeignKey("MålgruppeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adresseliste");

                    b.Navigation("Målgruppe");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.TargetGroup", b =>
                {
                    b.HasOne("Kontaktlisteregisteret.Web.Data.Virksomhet", "Virksomhet")
                        .WithMany()
                        .HasForeignKey("VirksomhetId");

                    b.Navigation("Virksomhet");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.TargetGroupMember", b =>
                {
                    b.HasOne("Kontaktlisteregisteret.Web.Data.Recipient", "Recipient")
                        .WithMany("Memberships")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontaktlisteregisteret.Web.Data.TargetGroup", "TargetGroup")
                        .WithMany("Members")
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.Abonnementsliste", b =>
                {
                    b.Navigation("Abonnenter");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.Adresseliste", b =>
                {
                    b.Navigation("Abonnementslister");

                    b.Navigation("Mottakere");

                    b.Navigation("Målgrupper");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.Recipient", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Kontaktlisteregisteret.Web.Data.TargetGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
